--- # ---------------------------------------------------------------------------
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: tf.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Buyer
  # ---------------------------------------------------------------------------
  - Name: Buyer
    Domain: buyer.tf.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Seller
  # ---------------------------------------------------------------------------
  - Name: Seller
    Domain: seller.tf.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Buyer Bank
  # ---------------------------------------------------------------------------
  - Name: BuyerBank
    Domain: buyerBank.tf.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Seller Bank
  # --------------------------------------------------------------------------
  - Name: SellerBank
    Domain: sellerBank.tf.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: ShippingCompany
    Domain: shipping.tf.com
    Template:
      Count: 1
    Users:
      Count: 1